package iplpackage;

public enum SortingTypes {
    Average, NO_OF_SIXES_AND_FOURS, HIGHEST_STRIKERATE_BASED_ON_FOURSANDSIXES, HIGHEST_AVERAGE_BASED_ON_HIGHEST_STRIKERATE, MAXIMUM_RUNS_AND_BESTAVERAGE, PLAYER,BATSMAN, BESTAVERAGE_IN_BOWLERS, BOWLER
}
