package iplpackage;

public enum SortingTypes {
    Average, NO_OF_SIXES_AND_FOURS, HIGHEST_STRIKERATE_BASED_ON_FOURSANDSIXES,
    HIGHEST_AVERAGE_BASED_ON_HIGHEST_STRIKERATE, MAXIMUM_RUNS_AND_BESTAVERAGE,
    PLAYER,BATSMAN, BESTAVERAGE_IN_BOWLERS, BESTSTRIKE_RATE_IN_BOWLERS,
    BESTECONOMY_IN_BOWLERS, BESTSTRIKE_RATE_WITH4AND6,
    BEST_AVERGAE_BESTSTRIKE_RATE, MAX_WICKETS_AND_BEST_AVERAGE,
    BEST_ALLROUNDER_AVERAGE, ALL_ROUNDER_BASED_ON_RUNS_AND_WICKETS, BOWLER
}
